// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD97m7nvCOOD0XBu6OC_DSzxEt9a9H7bsw',
    appId: '1:775863171003:web:f99aa86d99665a0542f69e',
    messagingSenderId: '775863171003',
    projectId: 'lista-tarea-fcd4a',
    authDomain: 'lista-tarea-fcd4a.firebaseapp.com',
    storageBucket: 'lista-tarea-fcd4a.firebasestorage.app',
    measurementId: 'G-G6J0EEB1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQdTmcrHpwKuGvYIUYJXQviS8-H-nDVk',
    appId: '1:775863171003:android:03f04b50a778f32342f69e',
    messagingSenderId: '775863171003',
    projectId: 'lista-tarea-fcd4a',
    storageBucket: 'lista-tarea-fcd4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-C2JJlfO5WIeaJKfRKg1lT_qcjU0C4po',
    appId: '1:775863171003:ios:7d7e2130c147f5a642f69e',
    messagingSenderId: '775863171003',
    projectId: 'lista-tarea-fcd4a',
    storageBucket: 'lista-tarea-fcd4a.firebasestorage.app',
    iosBundleId: 'com.example.diaADia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-C2JJlfO5WIeaJKfRKg1lT_qcjU0C4po',
    appId: '1:775863171003:ios:7d7e2130c147f5a642f69e',
    messagingSenderId: '775863171003',
    projectId: 'lista-tarea-fcd4a',
    storageBucket: 'lista-tarea-fcd4a.firebasestorage.app',
    iosBundleId: 'com.example.diaADia',
  );
}
